export const ADMIN_ROLES = {
  SUPER_ADMIN: 'super_admin',
  KIOSK_ADMIN: 'kiosk_admin',
  DEPARTMENT_HEAD: 'department_head',
  DEPARTMENT_OFFICER: 'department_officer',
  FIELD_OFFICER: 'field_officer',
  AUDITOR: 'auditor',
  SECURITY_ANALYST: 'security_analyst',
  SUPPORT_STAFF: 'support_staff',
};

export const ADMIN_DASHBOARD_PATHS = {
  [ADMIN_ROLES.SUPER_ADMIN]: '/admin/super',
  [ADMIN_ROLES.KIOSK_ADMIN]: '/admin/kiosk-ops',
  [ADMIN_ROLES.DEPARTMENT_HEAD]: '/admin/department',
  [ADMIN_ROLES.DEPARTMENT_OFFICER]: '/admin/officer',
  [ADMIN_ROLES.FIELD_OFFICER]: '/admin/officer',
  [ADMIN_ROLES.AUDITOR]: '/admin/audit',
  [ADMIN_ROLES.SECURITY_ANALYST]: '/admin/security',
  [ADMIN_ROLES.SUPPORT_STAFF]: '/admin/kiosk-ops',
};

export const ADMIN_PERMISSIONS = {
  SYSTEM_ALL: 'system.all',
  APPLICATION_READ_ALL: 'application.read.all',
  APPLICATION_READ_DEPARTMENT: 'application.read.department',
  APPLICATION_ASSIGN: 'application.assign',
  APPLICATION_WORKFLOW_ACTION: 'application.workflow.action',
  APPLICATION_ESCALATE: 'application.escalate',
  DOCUMENT_READ: 'document.read',
  DOCUMENT_VERIFY: 'document.verify',
  DOCUMENT_APPROVE: 'document.approve',
  DOCUMENT_DOWNLOAD: 'document.download',
  KIOSK_MONITOR: 'kiosk.monitor',
  KIOSK_DIAGNOSTICS: 'kiosk.diagnostics',
  KIOSK_REMOTE_ACTIONS: 'kiosk.remote.actions',
  SECURITY_MONITOR: 'security.monitor',
  AUDIT_READ: 'audit.read',
  QUEUE_MANAGE: 'queue.manage',
  ANALYTICS_READ: 'analytics.read',
  OFFICER_ASSIGN: 'officer.assign',
  USER_MANAGE: 'user.manage',
};

export const ROLE_PERMISSION_MAP = {
  [ADMIN_ROLES.SUPER_ADMIN]: Object.values(ADMIN_PERMISSIONS),
  [ADMIN_ROLES.KIOSK_ADMIN]: [
    ADMIN_PERMISSIONS.KIOSK_MONITOR,
    ADMIN_PERMISSIONS.KIOSK_DIAGNOSTICS,
    ADMIN_PERMISSIONS.KIOSK_REMOTE_ACTIONS,
    ADMIN_PERMISSIONS.ANALYTICS_READ,
  ],
  [ADMIN_ROLES.DEPARTMENT_HEAD]: [
    ADMIN_PERMISSIONS.APPLICATION_READ_DEPARTMENT,
    ADMIN_PERMISSIONS.APPLICATION_ASSIGN,
    ADMIN_PERMISSIONS.APPLICATION_WORKFLOW_ACTION,
    ADMIN_PERMISSIONS.APPLICATION_ESCALATE,
    ADMIN_PERMISSIONS.DOCUMENT_READ,
    ADMIN_PERMISSIONS.DOCUMENT_VERIFY,
    ADMIN_PERMISSIONS.DOCUMENT_APPROVE,
    ADMIN_PERMISSIONS.DOCUMENT_DOWNLOAD,
    ADMIN_PERMISSIONS.OFFICER_ASSIGN,
    ADMIN_PERMISSIONS.QUEUE_MANAGE,
    ADMIN_PERMISSIONS.ANALYTICS_READ,
  ],
  [ADMIN_ROLES.DEPARTMENT_OFFICER]: [
    ADMIN_PERMISSIONS.APPLICATION_READ_DEPARTMENT,
    ADMIN_PERMISSIONS.APPLICATION_WORKFLOW_ACTION,
    ADMIN_PERMISSIONS.DOCUMENT_READ,
    ADMIN_PERMISSIONS.DOCUMENT_VERIFY,
    ADMIN_PERMISSIONS.DOCUMENT_DOWNLOAD,
    ADMIN_PERMISSIONS.ANALYTICS_READ,
  ],
  [ADMIN_ROLES.FIELD_OFFICER]: [
    ADMIN_PERMISSIONS.APPLICATION_READ_DEPARTMENT,
    ADMIN_PERMISSIONS.APPLICATION_WORKFLOW_ACTION,
    ADMIN_PERMISSIONS.DOCUMENT_READ,
  ],
  [ADMIN_ROLES.AUDITOR]: [ADMIN_PERMISSIONS.AUDIT_READ, ADMIN_PERMISSIONS.ANALYTICS_READ],
  [ADMIN_ROLES.SECURITY_ANALYST]: [ADMIN_PERMISSIONS.SECURITY_MONITOR, ADMIN_PERMISSIONS.AUDIT_READ],
  [ADMIN_ROLES.SUPPORT_STAFF]: [ADMIN_PERMISSIONS.KIOSK_MONITOR, ADMIN_PERMISSIONS.KIOSK_DIAGNOSTICS],
};

export const WORKFLOW_STATES = {
  SUBMITTED: 'Submitted',
  ASSIGNED: 'Assigned',
  UNDER_REVIEW: 'Under Review',
  VERIFICATION_PENDING: 'Verification Pending',
  DOCUMENTS_REQUESTED: 'Documents Requested',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  ESCALATED: 'Escalated',
  COMPLETED: 'Completed',
};

